# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        stages: [pre-commit]
    -   id: end-of-file-fixer
        stages: [pre-commit]
    -   id: check-yaml
        stages: [pre-commit]
    -   id: debug-statements
        stages: [pre-commit]
    -   id: name-tests-test
        stages: [pre-commit]
        args: [--pytest-test-first]
    -   id: check-added-large-files
        args: ['--maxkb=2000']
        stages: [pre-commit]
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.7.0
    hooks:
    -   id: setup-cfg-fmt
        stages: [pre-commit]

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma
        stages: [pre-commit]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
    -   id: pyupgrade
        args: [--py311-plus]
        stages: [pre-commit]

-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    -   id: flake8
        stages: [pre-commit]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
    -   id: mypy
        stages: [pre-commit]
        pass_filenames: false
        args: ['frontend', 'backend']
        additional_dependencies:
        - types-requests
        - types-PyYAML
        - types-toml
        - types-aiofiles
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
    -   id: bandit
        stages: [pre-commit]
        args: [--configfile, .bandit, '--exclude', 'tests/']
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
    -   id: ruff-format
        stages: [pre-commit]
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi]
        require_serial: true
        stages: [pre-commit]
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: ["--line-length", "120"]
        stages: [pre-commit]

# Documentation validation hooks
-   repo: local
    hooks:
    -   id: validate-docs
        name: Validate documentation quality
        entry: python scripts/validate_docs.py --config scripts/validation_config.yml
        language: system
        files: ^docs/.*\.md$|^mkdocs\.yml$|^scripts/validation_config\.yml$
        stages: [pre-commit]
        pass_filenames: false
    -   id: markdownlint
        name: Lint markdown files
        entry: markdownlint
        language: node
        files: ^docs/.*\.md$
        additional_dependencies: ['markdownlint-cli']
        stages: [pre-commit]
    -   id: check-mkdocs-build
        name: Check MkDocs build
        entry: mkdocs build --strict
        language: system
        files: ^docs/.*\.md$|^mkdocs\.yml$
        pass_filenames: false
        stages: [pre-commit]
    -   id: check-doc-links
        name: Check documentation links
        entry: python scripts/check_links.py --no-external
        language: system
        files: ^docs/.*\.md$
        pass_filenames: false
        stages: [pre-commit]
