version: '3.8'

# Local development with simplified nginx (no SSL)
services:
  backend:
    image: culicidaelab-backend:${VERSION:-latest}
    container_name: culicidaelab_backend_local
    restart: "no"
    environment:
      - CULICIDAELAB_DATABASE_PATH=/app/backend/data/.lancedb
      - CULICIDAELAB_BACKEND_CORS_ORIGINS=http://localhost,http://localhost:8765,http://127.0.0.1,http://127.0.0.1:8765,http://localhost:3000,http://127.0.0.1:3000
      - CULICIDAELAB_SAVE_PREDICTED_IMAGES=true
      - PYTHONPATH=/app
      - FASTAPI_ENV=development
      - DEBUG=true
      - STATIC_URL_BASE=http://localhost
    volumes:
      - ./backend/data:/app/backend/data:rw
      - ./backend/static:/app/backend/static:rw
    networks:
      - culicidaelab_network
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 10s
      start_period: 10s
      retries: 3

  frontend:
    image: culicidaelab-frontend:${VERSION:-latest}
    container_name: culicidaelab_frontend_local
    restart: "no"
    environment:
      - CLIENT_BACKEND_URL=http://localhost  # For client-side (browser) requests via nginx
      - SERVER_BACKEND_URL=http://backend:8000  # For server-side requests within Docker network
      - STATIC_FILES_URL=http://localhost  # Static files served via nginx
      - SOLARA_DEBUG=true
      - SOLARA_ASSETS_PROXY=false
      - HOME=/app
    networks:
      - culicidaelab_network
    ports:
      - "8765:8765"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/"]
      interval: 60s
      timeout: 10s
      start_period: 10s
      retries: 3
    depends_on:
      - backend

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile.local
    container_name: culicidaelab_nginx_local
    restart: "no"
    ports:
      - "80:80"
    networks:
      - culicidaelab_network
    environment:
      - NGINX_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 60s
      timeout: 10s
      start_period: 5s
      retries: 3
    depends_on:
      - backend
      - frontend

networks:
  culicidaelab_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
