site_name: CulicidaeLab Server Documentation
site_description: Comprehensive documentation for the CulicidaeLab Server - A sophisticated web platform for mosquito research, surveillance, and data analysis
site_url: https://culicidaelab.github.io/CulicidaeLab-Server/
repo_url: https://github.com/CulicidaeLab/CulicidaeLab-Server
repo_name: CulicidaeLab/CulicidaeLab-Server
edit_uri: edit/main/docs/

# Navigation structure
nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - Overview: user-guide/overview.md
    - Species Prediction: user-guide/species-prediction.md
    - Map Visualization: user-guide/map-visualization.md
    - Data Management: user-guide/data-management.md
    - Troubleshooting: user-guide/troubleshooting.md
  - Developer Guide:
    - Architecture: developer-guide/architecture.md
    - API Reference:
      - Overview: developer-guide/api-reference/index.md
      - OpenAPI Integration: developer-guide/api-reference/openapi.md
      - Code Examples: developer-guide/api-reference/examples.md
      - Species API: developer-guide/api-reference/species.md
      - Diseases API: developer-guide/api-reference/diseases.md
      - Geographic API: developer-guide/api-reference/geo.md
      - Prediction API: developer-guide/api-reference/prediction.md
      - Observation API: developer-guide/api-reference/observation.md
      - Filters API: developer-guide/api-reference/filters.md
    - Frontend Development: developer-guide/frontend-development.md
    - Backend Development: developer-guide/backend-development.md
    - Testing: developer-guide/testing.md
    - Contributing: developer-guide/contributing.md
  - Deployment:
    - Production: deployment/production.md
    - Docker: deployment/docker.md
    - Monitoring: deployment/monitoring.md
    - Security: deployment/security.md
  - Research:
    - Data Models: research/data-models.md
    - AI Models: research/ai-models.md
    - Datasets: research/datasets.md
    - Ecosystem: research/ecosystem.md
  - Reference:
    - API: reference/api/index.md
    - Configuration: reference/configuration.md
    - Tags: reference/tags.md
    - Changelog: reference/changelog.md
    - Glossary: reference/glossary.md

# Theme configuration
theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
    logo: material/bug
  favicon: assets/favicon.ico
  custom_dir: docs/overrides

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang: en
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      fallback_to_build_date: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: false
            merge_init_into_class: true
            extra:
              paths: [backend, frontend]
              import:
                - https://docs.python.org/3/objects.inv
                - https://fastapi.tiangolo.com/objects.inv
  - mermaid2:
      arguments:
        theme: |
          ^(JSON.parse(__md_get("__palette").index == 1)) ?
          'dark' : 'light'
  - swagger-ui-tag
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
  - redirects:
      redirect_maps:
        'old-api.md': 'reference/api/index.md'
  - tags
  - social:
      cards: false
  - offline:
      enabled: false
  - meta

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page

  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: CulicidaeLab
      repo: CulicidaeLab-Server
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CulicidaeLab/CulicidaeLab-Server
      name: GitHub Repository
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact@culicidaelab.org
      name: Contact Us
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/culicidaelab
      name: Follow on Twitter
    - icon: fontawesome/solid/globe
      link: https://culicidaelab.org
      name: CulicidaeLab Website
  version:
    provider: mike
    default: latest
  generator: false
  analytics:
    provider: google
    property: G-XXXXXXXXXX
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            <a href="https://github.com/CulicidaeLab/CulicidaeLab-Server/issues/new/?title=[Docs Feedback] {title} - {url}" target="_blank" rel="noopener">telling us what you found helpful or what could be improved</a>.
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

# Copyright
copyright: Copyright &copy; 2024 CulicidaeLab

# Build settings
strict: false
use_directory_urls: true

# Custom CSS and JavaScript
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/navigation-enhancements.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
