# Docker Security Policy Configuration
# Defines security standards and requirements for all containers

security_standards:
  # Base image requirements
  base_images:
    allowed_registries:
      - "docker.io"
      - "registry.hub.docker.com"

    prohibited_tags:
      - "latest"
      - "master"
      - "main"

    required_updates:
      - "security_patches"
      - "critical_vulnerabilities"

  # User and permissions
  user_security:
    # Never run as root in production
    prohibit_root_user: true

    # Use specific UID/GID
    required_uid_range:
      min: 1000
      max: 65535

    # Minimal shell access
    preferred_shell: "/bin/false"

    # Home directory restrictions
    no_home_directory: true

  # File system security
  filesystem:
    # Read-only root filesystem where possible
    readonly_root_fs: true

    # Temporary filesystem for writable areas
    use_tmpfs: true

    # File permissions
    max_file_permissions: "755"
    max_dir_permissions: "750"

    # Remove unnecessary files
    cleanup_requirements:
      - "package_caches"
      - "temporary_files"
      - "build_dependencies"
      - "documentation"

  # Network security
  network:
    # Minimal port exposure
    expose_only_required_ports: true

    # No privileged ports
    prohibit_privileged_ports: true

    # Specific network interfaces
    bind_specific_interfaces: true

  # Runtime security
  runtime:
    # Resource limits
    require_resource_limits: true

    # Security options
    required_security_opts:
      - "no-new-privileges:true"

    # Capabilities
    drop_all_capabilities: true
    add_only_required_capabilities: true

    # AppArmor/SELinux
    use_security_profiles: true

# Vulnerability management
vulnerability_policy:
  # Severity thresholds
  max_allowed_severity: "MEDIUM"

  # Critical vulnerabilities
  critical_response_time: "24h"
  high_response_time: "7d"
  medium_response_time: "30d"

  # Scanning frequency
  scan_frequency:
    production: "daily"
    staging: "weekly"
    development: "monthly"

  # Exclusions (with justification required)
  allowed_exclusions:
    - vulnerability_id: "CVE-YYYY-XXXX"
      justification: "Not applicable to our use case"
      expiry_date: "2024-12-31"

# Compliance requirements
compliance:
  # Security frameworks
  frameworks:
    - "CIS Docker Benchmark"
    - "NIST Cybersecurity Framework"

  # Audit requirements
  audit_logging: true
  security_scanning: true
  penetration_testing: true

  # Documentation requirements
  security_documentation:
    - "threat_model"
    - "security_architecture"
    - "incident_response_plan"
    - "vulnerability_management_process"

# Monitoring and alerting
monitoring:
  # Runtime monitoring
  container_monitoring: true
  process_monitoring: true
  network_monitoring: true
  file_integrity_monitoring: true

  # Security events
  security_alerts:
    - "privilege_escalation"
    - "suspicious_network_activity"
    - "unauthorized_file_access"
    - "container_escape_attempts"

  # Log aggregation
  centralized_logging: true
  log_retention: "90d"
  log_encryption: true
