# Prometheus configuration for container monitoring
# Monitors Docker containers and application metrics

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'culicidaelab-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Docker daemon metrics (if enabled)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s
    metrics_path: /metrics

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # Node exporter for host metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # Backend application metrics
  - job_name: 'culicidaelab-backend'
    static_configs:
      - targets: ['backend:8000']
    scrape_interval: 30s
    metrics_path: /api/metrics
    scrape_timeout: 10s

  # Frontend application metrics
  - job_name: 'culicidaelab-frontend'
    static_configs:
      - targets: ['frontend:8765']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s
    metrics_path: /metrics

  # Custom application metrics
  - job_name: 'culicidaelab-custom'
    static_configs:
      - targets: ['backend:8000']
    scrape_interval: 60s
    metrics_path: /api/custom-metrics
    scrape_timeout: 15s
