name: Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for git-revision-date-localized plugin

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocstrings[python] mkdocs-mermaid2-plugin \
                      mkdocs-minify-plugin mkdocs-git-revision-date-localized-plugin \
                      mkdocs-swagger-ui-tag fastapi
      - name: Install CulicidaeLab-Server
        run: git clone https://github.com/iloncka-ds/culicidaelab-server.git && cd culicidaelab-server && pip install -e .[docs]
      - name: Build English docs
        run: mkdocs build --config-file=mkdocs.en.yml --site-dir=temp_build/en

      - name: Build Russian docs
        run: mkdocs build --config-file=mkdocs.ru.yml --site-dir=temp_build/ru

      - name: Create language selector page
        run: |
          cat > temp_build/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>CulicidaeLab Server Documentation</title>
              <style>
                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                      display: flex;
                      justify-content: center;
                      align-items: center;
                      min-height: 100vh;
                      margin: 0;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                  }
                  .container {
                      background: white;
                      padding: 3rem;
                      border-radius: 1rem;
                      box-shadow: 0 20px 60px rgba(0,0,0,0.3);
                      text-align: center;
                      max-width: 500px;
                  }
                  h1 { color: #333; margin-bottom: 2rem; font-size: 2rem; }
                  .lang-buttons { display: flex; gap: 1rem; justify-content: center; }
                  .lang-button {
                      display: inline-block;
                      padding: 1rem 2rem;
                      background: #667eea;
                      color: white;
                      text-decoration: none;
                      border-radius: 0.5rem;
                      font-weight: 600;
                      transition: transform 0.2s;
                      min-width: 150px;
                  }
                  .lang-button:hover {
                      transform: translateY(-2px);
                      background: #5568d3;
                  }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>🦟 CulicidaeLab Server</h1>
                  <p style="color: #666; margin-bottom: 2rem;">Select language / Выберите язык</p>
                  <div class="lang-buttons">
                      <a href="en/" class="lang-button">🇬🇧 English</a>
                      <a href="ru/" class="lang-button">🇷🇺 Русский</a>
                  </div>
              </div>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./temp_build
          force_orphan: true
